/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WorldInPaperAbi } from "./WorldInPaperAbi";
export * as factories from "./factories";
export { WorldInPaperAbi__factory } from "./factories/WorldInPaperAbi__factory";
