/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace WorldInPaper {
  export type GameViewStruct = {
    id: BigNumberish;
    entryAmount: BigNumberish;
    startingWIPBalance: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    maxPlayers: BigNumberish;
    playerCount: BigNumberish;
    creator: AddressLike;
    exists: boolean;
  };

  export type GameViewStructOutput = [
    id: bigint,
    entryAmount: bigint,
    startingWIPBalance: bigint,
    startTime: bigint,
    endTime: bigint,
    maxPlayers: bigint,
    playerCount: bigint,
    creator: string,
    exists: boolean
  ] & {
    id: bigint;
    entryAmount: bigint;
    startingWIPBalance: bigint;
    startTime: bigint;
    endTime: bigint;
    maxPlayers: bigint;
    playerCount: bigint;
    creator: string;
    exists: boolean;
  };

  export type GameRankingEntryViewStruct = {
    player: AddressLike;
    place: BigNumberish;
    wipBalance: BigNumberish;
  };

  export type GameRankingEntryViewStructOutput = [
    player: string,
    place: bigint,
    wipBalance: bigint
  ] & { player: string; place: bigint; wipBalance: bigint };

  export type TradeStruct = {
    id: BigNumberish;
    trader: AddressLike;
    asset_address: string;
    origin: BigNumberish;
    isBuy: boolean;
    amountIn: BigNumberish;
    amountOut: BigNumberish;
  };

  export type TradeStructOutput = [
    id: bigint,
    trader: string,
    asset_address: string,
    origin: bigint,
    isBuy: boolean,
    amountIn: bigint,
    amountOut: bigint
  ] & {
    id: bigint;
    trader: string;
    asset_address: string;
    origin: bigint;
    isBuy: boolean;
    amountIn: bigint;
    amountOut: bigint;
  };

  export type PortfolioTokenViewStruct = {
    asset_address: string;
    origin: BigNumberish;
    balance: BigNumberish;
    trades: WorldInPaper.TradeStruct[];
  };

  export type PortfolioTokenViewStructOutput = [
    asset_address: string,
    origin: bigint,
    balance: bigint,
    trades: WorldInPaper.TradeStructOutput[]
  ] & {
    asset_address: string;
    origin: bigint;
    balance: bigint;
    trades: WorldInPaper.TradeStructOutput[];
  };

  export type PlayerPortfolioViewStruct = {
    gameId: BigNumberish;
    player: AddressLike;
    wipBalance: BigNumberish;
    claimed: boolean;
    claimableAmount: BigNumberish;
    tokens: WorldInPaper.PortfolioTokenViewStruct[];
  };

  export type PlayerPortfolioViewStructOutput = [
    gameId: bigint,
    player: string,
    wipBalance: bigint,
    claimed: boolean,
    claimableAmount: bigint,
    tokens: WorldInPaper.PortfolioTokenViewStructOutput[]
  ] & {
    gameId: bigint;
    player: string;
    wipBalance: bigint;
    claimed: boolean;
    claimableAmount: bigint;
    tokens: WorldInPaper.PortfolioTokenViewStructOutput[];
  };

  export type TradeToSettleStruct = {
    id: BigNumberish;
    gameId: BigNumberish;
    trader: AddressLike;
    asset_address: string;
    origin: BigNumberish;
    amountIn: BigNumberish;
    isBuy: boolean;
  };

  export type TradeToSettleStructOutput = [
    id: bigint,
    gameId: bigint,
    trader: string,
    asset_address: string,
    origin: bigint,
    amountIn: bigint,
    isBuy: boolean
  ] & {
    id: bigint;
    gameId: bigint;
    trader: string;
    asset_address: string;
    origin: bigint;
    amountIn: bigint;
    isBuy: boolean;
  };

  export type WorldIdVerificationStruct = {
    nullifier: BigNumberish;
    action: BigNumberish;
    rpId: BigNumberish;
    nonce: BigNumberish;
    signalHash: BigNumberish;
    expiresAtMin: BigNumberish;
    issuerSchemaId: BigNumberish;
    credentialGenesisIssuedAtMin: BigNumberish;
    zeroKnowledgeProof: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ];
  };

  export type WorldIdVerificationStructOutput = [
    nullifier: bigint,
    action: bigint,
    rpId: bigint,
    nonce: bigint,
    signalHash: bigint,
    expiresAtMin: bigint,
    issuerSchemaId: bigint,
    credentialGenesisIssuedAtMin: bigint,
    zeroKnowledgeProof: [bigint, bigint, bigint, bigint, bigint]
  ] & {
    nullifier: bigint;
    action: bigint;
    rpId: bigint;
    nonce: bigint;
    signalHash: bigint;
    expiresAtMin: bigint;
    issuerSchemaId: bigint;
    credentialGenesisIssuedAtMin: bigint;
    zeroKnowledgeProof: [bigint, bigint, bigint, bigint, bigint];
  };
}

export interface WorldInPaperAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EXECUTION_PRICE_PRECISION"
      | "MAX_PLAYERS"
      | "MAX_STARTING_WIP_BALANCE"
      | "MIN_PLAYERS"
      | "MIN_STARTING_WIP_BALANCE"
      | "USDC"
      | "claimGame"
      | "createGame"
      | "getExpectedAuthor"
      | "getExpectedWorkflowId"
      | "getExpectedWorkflowName"
      | "getForwarderAddress"
      | "getGame"
      | "getGamePlayers"
      | "getGameRanking"
      | "getGameTradeCount"
      | "getGameTrades"
      | "getPlayerPortfolio"
      | "getTotalSettlementRequestsCreated"
      | "getTradeToSettle"
      | "hasJoined"
      | "joinGame"
      | "nextGameId"
      | "nextTradeToSettleId"
      | "nullifierUsed"
      | "onReport"
      | "owner"
      | "renounceOwnership"
      | "setExpectedAuthor"
      | "setExpectedWorkflowId"
      | "setExpectedWorkflowName"
      | "setForwarderAddress"
      | "submitTrade"
      | "supportsInterface"
      | "transferOwnership"
      | "verifier"
      | "worldIdVerificationEnabled"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExpectedAuthorUpdated"
      | "ExpectedWorkflowIdUpdated"
      | "ExpectedWorkflowNameUpdated"
      | "ForwarderAddressUpdated"
      | "GameClaimed"
      | "GameCreated"
      | "GameJoined"
      | "OwnershipTransferred"
      | "SecurityWarning"
      | "SettlementRequest"
      | "TradeRecorded"
      | "TradeSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EXECUTION_PRICE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PLAYERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_STARTING_WIP_BALANCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PLAYERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_STARTING_WIP_BALANCE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedAuthor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedWorkflowId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedWorkflowName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getForwarderAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGamePlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameRanking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameTradeCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameTrades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerPortfolio",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSettlementRequestsCreated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeToSettle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasJoined",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextGameId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextTradeToSettleId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nullifierUsed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onReport",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedAuthor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedWorkflowId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedWorkflowName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setForwarderAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTrade",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      boolean,
      BigNumberish,
      WorldInPaper.WorldIdVerificationStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "worldIdVerificationEnabled",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "EXECUTION_PRICE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PLAYERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STARTING_WIP_BALANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PLAYERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_STARTING_WIP_BALANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedAuthor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedWorkflowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedWorkflowName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getForwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGamePlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGameRanking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGameTradeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGameTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerPortfolio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSettlementRequestsCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradeToSettle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasJoined", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextGameId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTradeToSettleId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onReport", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedAuthor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedWorkflowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedWorkflowName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setForwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "worldIdVerificationEnabled",
    data: BytesLike
  ): Result;
}

export namespace ExpectedAuthorUpdatedEvent {
  export type InputTuple = [
    previousAuthor: AddressLike,
    newAuthor: AddressLike
  ];
  export type OutputTuple = [previousAuthor: string, newAuthor: string];
  export interface OutputObject {
    previousAuthor: string;
    newAuthor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpectedWorkflowIdUpdatedEvent {
  export type InputTuple = [previousId: BytesLike, newId: BytesLike];
  export type OutputTuple = [previousId: string, newId: string];
  export interface OutputObject {
    previousId: string;
    newId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpectedWorkflowNameUpdatedEvent {
  export type InputTuple = [previousName: BytesLike, newName: BytesLike];
  export type OutputTuple = [previousName: string, newName: string];
  export interface OutputObject {
    previousName: string;
    newName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForwarderAddressUpdatedEvent {
  export type InputTuple = [
    previousForwarder: AddressLike,
    newForwarder: AddressLike
  ];
  export type OutputTuple = [previousForwarder: string, newForwarder: string];
  export interface OutputObject {
    previousForwarder: string;
    newForwarder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameClaimedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    payout: BigNumberish,
    rank: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    payout: bigint,
    rank: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    payout: bigint;
    rank: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCreatedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    creator: AddressLike,
    entryAmount: BigNumberish,
    maxPlayers: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    creator: string,
    entryAmount: bigint,
    maxPlayers: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    creator: string;
    entryAmount: bigint;
    maxPlayers: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameJoinedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    playerCount: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    playerCount: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    playerCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityWarningEvent {
  export type InputTuple = [message: string];
  export type OutputTuple = [message: string];
  export interface OutputObject {
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementRequestEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    gameId: BigNumberish,
    asset_address: string,
    origin: BigNumberish,
    isBuy: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    gameId: bigint,
    asset_address: string,
    origin: bigint,
    isBuy: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    gameId: bigint;
    asset_address: string;
    origin: bigint;
    isBuy: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeRecordedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    tradeId: BigNumberish,
    trader: AddressLike,
    asset_address: string,
    origin: BigNumberish,
    isBuy: boolean,
    amountIn: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    tradeId: bigint,
    trader: string,
    asset_address: string,
    origin: bigint,
    isBuy: boolean,
    amountIn: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    tradeId: bigint;
    trader: string;
    asset_address: string;
    origin: bigint;
    isBuy: boolean;
    amountIn: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeSettledEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    trader: AddressLike,
    asset_address: string,
    origin: BigNumberish,
    amountIn: BigNumberish,
    isBuy: boolean,
    executionPrice: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    trader: string,
    asset_address: string,
    origin: bigint,
    amountIn: bigint,
    isBuy: boolean,
    executionPrice: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    trader: string;
    asset_address: string;
    origin: bigint;
    amountIn: bigint;
    isBuy: boolean;
    executionPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldInPaperAbi extends BaseContract {
  connect(runner?: ContractRunner | null): WorldInPaperAbi;
  waitForDeployment(): Promise<this>;

  interface: WorldInPaperAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EXECUTION_PRICE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  MAX_PLAYERS: TypedContractMethod<[], [bigint], "view">;

  MAX_STARTING_WIP_BALANCE: TypedContractMethod<[], [bigint], "view">;

  MIN_PLAYERS: TypedContractMethod<[], [bigint], "view">;

  MIN_STARTING_WIP_BALANCE: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  claimGame: TypedContractMethod<
    [gameId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  createGame: TypedContractMethod<
    [
      entryAmount: BigNumberish,
      startingWIPBalance: BigNumberish,
      maxPlayers: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getExpectedAuthor: TypedContractMethod<[], [string], "view">;

  getExpectedWorkflowId: TypedContractMethod<[], [string], "view">;

  getExpectedWorkflowName: TypedContractMethod<[], [string], "view">;

  getForwarderAddress: TypedContractMethod<[], [string], "view">;

  getGame: TypedContractMethod<
    [gameId: BigNumberish],
    [WorldInPaper.GameViewStructOutput],
    "view"
  >;

  getGamePlayers: TypedContractMethod<
    [gameId: BigNumberish],
    [string[]],
    "view"
  >;

  getGameRanking: TypedContractMethod<
    [gameId: BigNumberish],
    [WorldInPaper.GameRankingEntryViewStructOutput[]],
    "view"
  >;

  getGameTradeCount: TypedContractMethod<
    [gameId: BigNumberish],
    [bigint],
    "view"
  >;

  getGameTrades: TypedContractMethod<
    [gameId: BigNumberish],
    [WorldInPaper.TradeStructOutput[]],
    "view"
  >;

  getPlayerPortfolio: TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [WorldInPaper.PlayerPortfolioViewStructOutput],
    "view"
  >;

  getTotalSettlementRequestsCreated: TypedContractMethod<[], [bigint], "view">;

  getTradeToSettle: TypedContractMethod<
    [tradeId: BigNumberish],
    [WorldInPaper.TradeToSettleStructOutput],
    "view"
  >;

  hasJoined: TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [boolean],
    "view"
  >;

  joinGame: TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;

  nextGameId: TypedContractMethod<[], [bigint], "view">;

  nextTradeToSettleId: TypedContractMethod<[], [bigint], "view">;

  nullifierUsed: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  onReport: TypedContractMethod<
    [metadata: BytesLike, report: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setExpectedAuthor: TypedContractMethod<
    [_author: AddressLike],
    [void],
    "nonpayable"
  >;

  setExpectedWorkflowId: TypedContractMethod<
    [_id: BytesLike],
    [void],
    "nonpayable"
  >;

  setExpectedWorkflowName: TypedContractMethod<
    [_name: string],
    [void],
    "nonpayable"
  >;

  setForwarderAddress: TypedContractMethod<
    [_forwarder: AddressLike],
    [void],
    "nonpayable"
  >;

  submitTrade: TypedContractMethod<
    [
      gameId: BigNumberish,
      asset_address: string,
      origin: BigNumberish,
      isBuy: boolean,
      amountIn: BigNumberish,
      worldId: WorldInPaper.WorldIdVerificationStruct
    ],
    [bigint],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  worldIdVerificationEnabled: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EXECUTION_PRICE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PLAYERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STARTING_WIP_BALANCE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PLAYERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STARTING_WIP_BALANCE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimGame"
  ): TypedContractMethod<[gameId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [
      entryAmount: BigNumberish,
      startingWIPBalance: BigNumberish,
      maxPlayers: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getExpectedAuthor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getExpectedWorkflowId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getExpectedWorkflowName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getForwarderAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [WorldInPaper.GameViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGamePlayers"
  ): TypedContractMethod<[gameId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getGameRanking"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [WorldInPaper.GameRankingEntryViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGameTradeCount"
  ): TypedContractMethod<[gameId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGameTrades"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [WorldInPaper.TradeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerPortfolio"
  ): TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [WorldInPaper.PlayerPortfolioViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalSettlementRequestsCreated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTradeToSettle"
  ): TypedContractMethod<
    [tradeId: BigNumberish],
    [WorldInPaper.TradeToSettleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasJoined"
  ): TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextGameId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextTradeToSettleId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nullifierUsed"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "onReport"
  ): TypedContractMethod<
    [metadata: BytesLike, report: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpectedAuthor"
  ): TypedContractMethod<[_author: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpectedWorkflowId"
  ): TypedContractMethod<[_id: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpectedWorkflowName"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setForwarderAddress"
  ): TypedContractMethod<[_forwarder: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitTrade"
  ): TypedContractMethod<
    [
      gameId: BigNumberish,
      asset_address: string,
      origin: BigNumberish,
      isBuy: boolean,
      amountIn: BigNumberish,
      worldId: WorldInPaper.WorldIdVerificationStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "worldIdVerificationEnabled"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "ExpectedAuthorUpdated"
  ): TypedContractEvent<
    ExpectedAuthorUpdatedEvent.InputTuple,
    ExpectedAuthorUpdatedEvent.OutputTuple,
    ExpectedAuthorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpectedWorkflowIdUpdated"
  ): TypedContractEvent<
    ExpectedWorkflowIdUpdatedEvent.InputTuple,
    ExpectedWorkflowIdUpdatedEvent.OutputTuple,
    ExpectedWorkflowIdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpectedWorkflowNameUpdated"
  ): TypedContractEvent<
    ExpectedWorkflowNameUpdatedEvent.InputTuple,
    ExpectedWorkflowNameUpdatedEvent.OutputTuple,
    ExpectedWorkflowNameUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ForwarderAddressUpdated"
  ): TypedContractEvent<
    ForwarderAddressUpdatedEvent.InputTuple,
    ForwarderAddressUpdatedEvent.OutputTuple,
    ForwarderAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GameClaimed"
  ): TypedContractEvent<
    GameClaimedEvent.InputTuple,
    GameClaimedEvent.OutputTuple,
    GameClaimedEvent.OutputObject
  >;
  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameJoined"
  ): TypedContractEvent<
    GameJoinedEvent.InputTuple,
    GameJoinedEvent.OutputTuple,
    GameJoinedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SecurityWarning"
  ): TypedContractEvent<
    SecurityWarningEvent.InputTuple,
    SecurityWarningEvent.OutputTuple,
    SecurityWarningEvent.OutputObject
  >;
  getEvent(
    key: "SettlementRequest"
  ): TypedContractEvent<
    SettlementRequestEvent.InputTuple,
    SettlementRequestEvent.OutputTuple,
    SettlementRequestEvent.OutputObject
  >;
  getEvent(
    key: "TradeRecorded"
  ): TypedContractEvent<
    TradeRecordedEvent.InputTuple,
    TradeRecordedEvent.OutputTuple,
    TradeRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TradeSettled"
  ): TypedContractEvent<
    TradeSettledEvent.InputTuple,
    TradeSettledEvent.OutputTuple,
    TradeSettledEvent.OutputObject
  >;

  filters: {
    "ExpectedAuthorUpdated(address,address)": TypedContractEvent<
      ExpectedAuthorUpdatedEvent.InputTuple,
      ExpectedAuthorUpdatedEvent.OutputTuple,
      ExpectedAuthorUpdatedEvent.OutputObject
    >;
    ExpectedAuthorUpdated: TypedContractEvent<
      ExpectedAuthorUpdatedEvent.InputTuple,
      ExpectedAuthorUpdatedEvent.OutputTuple,
      ExpectedAuthorUpdatedEvent.OutputObject
    >;

    "ExpectedWorkflowIdUpdated(bytes32,bytes32)": TypedContractEvent<
      ExpectedWorkflowIdUpdatedEvent.InputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputObject
    >;
    ExpectedWorkflowIdUpdated: TypedContractEvent<
      ExpectedWorkflowIdUpdatedEvent.InputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputObject
    >;

    "ExpectedWorkflowNameUpdated(bytes10,bytes10)": TypedContractEvent<
      ExpectedWorkflowNameUpdatedEvent.InputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputObject
    >;
    ExpectedWorkflowNameUpdated: TypedContractEvent<
      ExpectedWorkflowNameUpdatedEvent.InputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputObject
    >;

    "ForwarderAddressUpdated(address,address)": TypedContractEvent<
      ForwarderAddressUpdatedEvent.InputTuple,
      ForwarderAddressUpdatedEvent.OutputTuple,
      ForwarderAddressUpdatedEvent.OutputObject
    >;
    ForwarderAddressUpdated: TypedContractEvent<
      ForwarderAddressUpdatedEvent.InputTuple,
      ForwarderAddressUpdatedEvent.OutputTuple,
      ForwarderAddressUpdatedEvent.OutputObject
    >;

    "GameClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      GameClaimedEvent.InputTuple,
      GameClaimedEvent.OutputTuple,
      GameClaimedEvent.OutputObject
    >;
    GameClaimed: TypedContractEvent<
      GameClaimedEvent.InputTuple,
      GameClaimedEvent.OutputTuple,
      GameClaimedEvent.OutputObject
    >;

    "GameCreated(uint256,address,uint256,uint16,uint256,uint256)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameJoined(uint256,address,uint16)": TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;
    GameJoined: TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SecurityWarning(string)": TypedContractEvent<
      SecurityWarningEvent.InputTuple,
      SecurityWarningEvent.OutputTuple,
      SecurityWarningEvent.OutputObject
    >;
    SecurityWarning: TypedContractEvent<
      SecurityWarningEvent.InputTuple,
      SecurityWarningEvent.OutputTuple,
      SecurityWarningEvent.OutputObject
    >;

    "SettlementRequest(uint256,uint256,string,uint8,bool,uint256)": TypedContractEvent<
      SettlementRequestEvent.InputTuple,
      SettlementRequestEvent.OutputTuple,
      SettlementRequestEvent.OutputObject
    >;
    SettlementRequest: TypedContractEvent<
      SettlementRequestEvent.InputTuple,
      SettlementRequestEvent.OutputTuple,
      SettlementRequestEvent.OutputObject
    >;

    "TradeRecorded(uint256,uint256,address,string,uint8,bool,uint256,uint256)": TypedContractEvent<
      TradeRecordedEvent.InputTuple,
      TradeRecordedEvent.OutputTuple,
      TradeRecordedEvent.OutputObject
    >;
    TradeRecorded: TypedContractEvent<
      TradeRecordedEvent.InputTuple,
      TradeRecordedEvent.OutputTuple,
      TradeRecordedEvent.OutputObject
    >;

    "TradeSettled(uint256,address,string,uint8,uint256,bool,uint256)": TypedContractEvent<
      TradeSettledEvent.InputTuple,
      TradeSettledEvent.OutputTuple,
      TradeSettledEvent.OutputObject
    >;
    TradeSettled: TypedContractEvent<
      TradeSettledEvent.InputTuple,
      TradeSettledEvent.OutputTuple,
      TradeSettledEvent.OutputObject
    >;
  };
}
