/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace WorldInPaper {
  export type GameViewStruct = {
    id: BigNumberish;
    entryAmount: BigNumberish;
    startingWIPBalance: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    maxPlayers: BigNumberish;
    playerCount: BigNumberish;
    creator: AddressLike;
    exists: boolean;
  };

  export type GameViewStructOutput = [
    id: bigint,
    entryAmount: bigint,
    startingWIPBalance: bigint,
    startTime: bigint,
    endTime: bigint,
    maxPlayers: bigint,
    playerCount: bigint,
    creator: string,
    exists: boolean
  ] & {
    id: bigint;
    entryAmount: bigint;
    startingWIPBalance: bigint;
    startTime: bigint;
    endTime: bigint;
    maxPlayers: bigint;
    playerCount: bigint;
    creator: string;
    exists: boolean;
  };

  export type GameRankingEntryViewStruct = {
    player: AddressLike;
    place: BigNumberish;
    wipBalance: BigNumberish;
  };

  export type GameRankingEntryViewStructOutput = [
    player: string,
    place: bigint,
    wipBalance: bigint
  ] & { player: string; place: bigint; wipBalance: bigint };

  export type TradeStruct = {
    id: BigNumberish;
    trader: AddressLike;
    asset_address: string;
    origin: BigNumberish;
    isBuy: boolean;
    amountIn: BigNumberish;
    amountOut: BigNumberish;
  };

  export type TradeStructOutput = [
    id: bigint,
    trader: string,
    asset_address: string,
    origin: bigint,
    isBuy: boolean,
    amountIn: bigint,
    amountOut: bigint
  ] & {
    id: bigint;
    trader: string;
    asset_address: string;
    origin: bigint;
    isBuy: boolean;
    amountIn: bigint;
    amountOut: bigint;
  };

  export type PortfolioTokenViewStruct = {
    asset_address: string;
    origin: BigNumberish;
    balance: BigNumberish;
    trades: WorldInPaper.TradeStruct[];
  };

  export type PortfolioTokenViewStructOutput = [
    asset_address: string,
    origin: bigint,
    balance: bigint,
    trades: WorldInPaper.TradeStructOutput[]
  ] & {
    asset_address: string;
    origin: bigint;
    balance: bigint;
    trades: WorldInPaper.TradeStructOutput[];
  };

  export type PlayerPortfolioViewStruct = {
    gameId: BigNumberish;
    player: AddressLike;
    wipBalance: BigNumberish;
    claimed: boolean;
    claimableAmount: BigNumberish;
    tokens: WorldInPaper.PortfolioTokenViewStruct[];
  };

  export type PlayerPortfolioViewStructOutput = [
    gameId: bigint,
    player: string,
    wipBalance: bigint,
    claimed: boolean,
    claimableAmount: bigint,
    tokens: WorldInPaper.PortfolioTokenViewStructOutput[]
  ] & {
    gameId: bigint;
    player: string;
    wipBalance: bigint;
    claimed: boolean;
    claimableAmount: bigint;
    tokens: WorldInPaper.PortfolioTokenViewStructOutput[];
  };
}

export interface WorldInPaperObserverAbiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCreatedGames"
      | "getGameRanking"
      | "getJoinedGames"
      | "getPlayerPortfolio"
      | "getRecentGames"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCreatedGames",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameRanking",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJoinedGames",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerPortfolio",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentGames",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCreatedGames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGameRanking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJoinedGames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerPortfolio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentGames",
    data: BytesLike
  ): Result;
}

export interface WorldInPaperObserverAbi extends BaseContract {
  connect(runner?: ContractRunner | null): WorldInPaperObserverAbi;
  waitForDeployment(): Promise<this>;

  interface: WorldInPaperObserverAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCreatedGames: TypedContractMethod<
    [world: AddressLike, creator: AddressLike, limit: BigNumberish],
    [WorldInPaper.GameViewStructOutput[]],
    "view"
  >;

  getGameRanking: TypedContractMethod<
    [world: AddressLike, gameId: BigNumberish],
    [WorldInPaper.GameRankingEntryViewStructOutput[]],
    "view"
  >;

  getJoinedGames: TypedContractMethod<
    [world: AddressLike, player: AddressLike, limit: BigNumberish],
    [WorldInPaper.GameViewStructOutput[]],
    "view"
  >;

  getPlayerPortfolio: TypedContractMethod<
    [world: AddressLike, gameId: BigNumberish, player: AddressLike],
    [WorldInPaper.PlayerPortfolioViewStructOutput],
    "view"
  >;

  getRecentGames: TypedContractMethod<
    [world: AddressLike, limit: BigNumberish],
    [WorldInPaper.GameViewStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCreatedGames"
  ): TypedContractMethod<
    [world: AddressLike, creator: AddressLike, limit: BigNumberish],
    [WorldInPaper.GameViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGameRanking"
  ): TypedContractMethod<
    [world: AddressLike, gameId: BigNumberish],
    [WorldInPaper.GameRankingEntryViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJoinedGames"
  ): TypedContractMethod<
    [world: AddressLike, player: AddressLike, limit: BigNumberish],
    [WorldInPaper.GameViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerPortfolio"
  ): TypedContractMethod<
    [world: AddressLike, gameId: BigNumberish, player: AddressLike],
    [WorldInPaper.PlayerPortfolioViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentGames"
  ): TypedContractMethod<
    [world: AddressLike, limit: BigNumberish],
    [WorldInPaper.GameViewStructOutput[]],
    "view"
  >;

  filters: {};
}
