/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  WorldInPaperObserverAbi,
  WorldInPaperObserverAbiInterface,
} from "../WorldInPaperObserverAbi";

const _abi = [
  {
    type: "function",
    name: "getCreatedGames",
    inputs: [
      {
        name: "world",
        type: "address",
        internalType: "contract WorldInPaper",
      },
      {
        name: "creator",
        type: "address",
        internalType: "address",
      },
      {
        name: "limit",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "games",
        type: "tuple[]",
        internalType: "struct WorldInPaper.GameView[]",
        components: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "entryAmount",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "startingWIPBalance",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "startTime",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "endTime",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxPlayers",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "playerCount",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "creator",
            type: "address",
            internalType: "address",
          },
          {
            name: "exists",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getGameRanking",
    inputs: [
      {
        name: "world",
        type: "address",
        internalType: "contract WorldInPaper",
      },
      {
        name: "gameId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "ranking",
        type: "tuple[]",
        internalType: "struct WorldInPaper.GameRankingEntryView[]",
        components: [
          {
            name: "player",
            type: "address",
            internalType: "address",
          },
          {
            name: "place",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "wipBalance",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getJoinedGames",
    inputs: [
      {
        name: "world",
        type: "address",
        internalType: "contract WorldInPaper",
      },
      {
        name: "player",
        type: "address",
        internalType: "address",
      },
      {
        name: "limit",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "games",
        type: "tuple[]",
        internalType: "struct WorldInPaper.GameView[]",
        components: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "entryAmount",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "startingWIPBalance",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "startTime",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "endTime",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxPlayers",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "playerCount",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "creator",
            type: "address",
            internalType: "address",
          },
          {
            name: "exists",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlayerPortfolio",
    inputs: [
      {
        name: "world",
        type: "address",
        internalType: "contract WorldInPaper",
      },
      {
        name: "gameId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "portfolio",
        type: "tuple",
        internalType: "struct WorldInPaper.PlayerPortfolioView",
        components: [
          {
            name: "gameId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "player",
            type: "address",
            internalType: "address",
          },
          {
            name: "wipBalance",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "claimed",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "claimableAmount",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "tokens",
            type: "tuple[]",
            internalType: "struct WorldInPaper.PortfolioTokenView[]",
            components: [
              {
                name: "asset_address",
                type: "string",
                internalType: "string",
              },
              {
                name: "origin",
                type: "uint8",
                internalType: "enum WorldInPaper.Origin",
              },
              {
                name: "balance",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "trades",
                type: "tuple[]",
                internalType: "struct WorldInPaper.Trade[]",
                components: [
                  {
                    name: "id",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "trader",
                    type: "address",
                    internalType: "address",
                  },
                  {
                    name: "asset_address",
                    type: "string",
                    internalType: "string",
                  },
                  {
                    name: "origin",
                    type: "uint8",
                    internalType: "enum WorldInPaper.Origin",
                  },
                  {
                    name: "isBuy",
                    type: "bool",
                    internalType: "bool",
                  },
                  {
                    name: "amountIn",
                    type: "uint256",
                    internalType: "uint256",
                  },
                  {
                    name: "amountOut",
                    type: "uint256",
                    internalType: "uint256",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRecentGames",
    inputs: [
      {
        name: "world",
        type: "address",
        internalType: "contract WorldInPaper",
      },
      {
        name: "limit",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "games",
        type: "tuple[]",
        internalType: "struct WorldInPaper.GameView[]",
        components: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "entryAmount",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "startingWIPBalance",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "startTime",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "endTime",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxPlayers",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "playerCount",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "creator",
            type: "address",
            internalType: "address",
          },
          {
            name: "exists",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "error",
    name: "NotGamePlayer",
    inputs: [
      {
        name: "gameId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "player",
        type: "address",
        internalType: "address",
      },
    ],
  },
] as const;

export class WorldInPaperObserverAbi__factory {
  static readonly abi = _abi;
  static createInterface(): WorldInPaperObserverAbiInterface {
    return new Interface(_abi) as WorldInPaperObserverAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): WorldInPaperObserverAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as WorldInPaperObserverAbi;
  }
}
